language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="0"
  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - git clone -b master-eficent https://github.com/Eficent/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
